-- AUTO-GENERATED from CHANGELOG.md -- do not edit by hand.
-- Regenerated by the release workflow at package time.
local _, TCC = ...
TCC.CHANGELOG = [==[
# Twisteds Combat Alerts - What's New

## 1.1.0

Combat Alerts drops its bundled spell/item database in favour of reading names live from your own spellbook, gear and bags - a much smaller download - and a few search, test and slash-command rough edges are fixed.

- **[BUG FIX]** **Alert visuals recycle.** An on-screen alert's frame is reused when you delete its rule, instead of lingering for the rest of the session.
- **[CHANGE]** **Lighter search, no bundled database.** The optional spell/item name database is gone; the **Find** search now reads live from your spellbook, auras, gear and bags - paste a numeric spell or item **ID** to add anything outside those. Much smaller install, and no data file to parse on first search.
- **[BUG FIX]** **/tap alerts** opens the manager again (it had stopped doing anything after the navigation move).
- **[BUG FIX]** **Test cues can be stopped again** - the on-screen **Stop Test** bar is back, so a looping test no longer runs until you /reload.
- **[CHANGE]** **Test button moved.** The test button now lives in the alert editor's header (reachable from any tab) and is labelled **Test Alert**.

## 1.0.1

- **[CHANGE]** Item and add-on lookups now use the current C_Item / C_AddOns APIs directly; the deprecated GetItemInfo / GetAddOnMetadata fallbacks were removed. No functional change.

## 1.0.0

- **[CHANGE]** Out of beta - Twisteds Combat Alerts is now a stable 1.0 release.

## 1.0.0-beta.3

- **[CHANGE]** **Tabbed layout.** The page is now split into tabs - **Alerts**, **Profiles**, and
  **Settings** - docked under the title bar, instead of one long scrolling page. Everything's in the
  same place, just quicker to get to.
- **[BUG FIX]** Picks up the latest shared appearance fixes - custom theme colors now save correctly
  from the color picker, and the **Menu scale** slider is smoother to drag.

## 1.0.0-beta.2

- **[BUG FIX]** Alerts can now be **per-character**. The **Profile** section at the top of the page
  lets you switch this character between **Account-wide** (shared by all your characters) and **This
  character** (private) - or your own named profiles - so alerts made on your Hunter no longer show
  up on your Healer.
- **[NEW]** **Find** search when building an alert - search your spellbook, auras, gear and bags
  (plus the platform's game database when it's loaded) and pick a spell or item instead of typing an
  ID. The lookup field shows a **live icon** of what you picked, and stores the ID so it keeps working
  in Mythic+.
- **[NEW]** Fresh platform look in Settings: pick a **shape** (sharp or rounded) and a **color
  scheme** (neutral greys, light themes, or a WoW-expansion palette), or set every color yourself,
  and scale the whole menu with **Menu scale**.
- **[BUG FIX]** Fixed cramped spacing on the **Text size** and **Icon size** sliders in the alert
  editor (the value readout no longer overlaps the row above).

## 2.1.1

- **[CHANGE]** Group-range checks (the "range to a group role" condition, e.g. "Healer/Tank
  out of range") are hidden. Due to Blizzard's API changes we can't make these work reliably
  across all content, so alerts now prefer a **spell-range check to your target** instead. Any
  existing group-range alert still runs, but you can no longer add new ones.

## 1.2.0-beta.3

- **[NEW]** The menu is now sorted into sections (Cues / Settings / Help & About) so
  pages are easier to find.
- **[NEW]** Resize and place the marker bar: a **Position & Size** button opens an
  on-screen mover - drag the panel to move the bar, and use its slider to resize it.
- **[NEW]** Choose when the marker bar shows: always, in any instance, in dungeons, in
  raids, or only while in a group.
- **[NEW]** The Help page now points you to our Discord and its AI assistant, with a
  one-click join button.
- **[CHANGE]** The marker bar's lock/unlock was replaced by the new Position & Size mover.

### Known issues

- **[KNOWN]** Resizing the marker bar can be a little rough - the scaling isn't perfectly
  smooth yet.
- **[KNOWN]** Range checks can give mixed results in some instances; we're still tuning how
  they behave there.

## 1.2.0-beta.2

- **[BUG FIX]** Fixed error spam in combat and dungeons ("secret value" Lua errors).
- **[BUG FIX]** Fixed scrolling in the Cue Manager - it previously only worked on the
  Getting Started page. Mouse wheel and the scrollbar work everywhere now.
- **[BUG FIX]** Focus call-out now works in combat. Your Party/Raid chat message was
  being blocked mid-fight; it sends reliably now.
- **[BUG FIX]** Range cues work in instances again. "Healer/Tank out of range" alerts
  now work in dungeons, raids, and scenarios, and the debug screen shows the real
  distance in yards.
- **[BUG FIX]** Marker palette remembers itself - if you close the on-screen marker
  bar, it stays closed after a reload (before, it kept coming back).
- **[NEW]** "What's New" page - browse recent updates right in the addon
  (sidebar > What's New).
- **[NEW]** "Tank in range" readout added to the debug screen.
- **[NEW]** Discord link in the footer - click it to copy an invite to the community
  server.
- **[CHANGE]** Focus call-out no longer inserts the target's name. Blizzard now hides
  unit names in combat, so the call-out shows just your marker icon (e.g. "Focus {skull}").

## 1.2.0-beta.1

- **[NEW]** First public beta.
]==]
